swagger: "2.0"
info:
  description: "A simple URL Shortener with loads of functionalities."
  version: "1.0.0"
  title: "Pink Panther URL Shortener"
host: "localhost:8080"
basePath: "/"
tags:
- name: "F1"
  description: |
    _Servicio de transformacion de URI a imagen QR_
    ### Secuencia de ejecución
    1. Al crear la URI recortada mediante un `POST /short`  me devuelven el enlace a la imagen QR si así lo solicita el cliente.
    1. Simultáneamente, `POST /short` invoca **asíncronamente** un servicio interno mediante el protocolo SOAP para que genere la imagen.
    1. Al devolver la respuesta se incluirá en el campo `qr` la dirección donde se puede encontrar que tendrá la forma `{base}/qr/{id}`
    1. Mediante `GET /qr/{id}` se obtendrá la imagen QR. Se devolverá 404 si dicho `id` no corresponde a una URL acortada o todavía no esta disponible la imagen. Si la imagen todavía no está disponible se notificará con `Retry-After` un tiempo prudencial para reinterar la petición.

- name: "F2"
  description: |
    Servicio que comprueba que una URL se puede alcanzar antes de crear una URL corta
    ### Secuencia de ejecución método `GET /{id}/alive`
      1. Al crear la URI recortada mediante un `POST /short`  con el parametro `periodicity` se activa el proceso interno para verificar de forma periodica la URI
      1. Al llamar al método `GET /{id}/alive` devuelve una JSON indicando el estado de la URI
      1. Si no se había creado la URI con la funcionalidad `periodicity` el método `GET /{id}/alive` devuelve 404.
- name: "F3"
  description: |
    Servicio que permite subir un CSV con todas las URI que se desean acortar y que devuelve un CSV con que contiene para cada URI su URI acortada. Si alguna URI es incorrecta se señalará en el mismo CSV.
    - Formato de entrada CSV:
      | URIOriginal |
      | ------- |
      | http://midomino.com |
      | noSoyUnaURI |
      | http://mirecurso.com |
    - Formato de salida CSV:
      | URIOriginal | URIAcortada |
      | ------- | -------- |
      | http://midomino.com | http://recortada/123 |+
      | noSoyUnaURI | Uri no disponible |
      | http://mirecurso.com | http://recortada/321 |

    - **Secuencia de ejecución**:
        1. Invocar a /uploadCSV
        2. Una vez se haya subido el fichero, se devolverá un identificador de tarea id.
        3. Se llama periodicamente a /job/{id} para comprobar el estado de la tarea.
        4. Una vez la tarea finalice /job/{id} le devolverá el identificador de la tarea acabada.
        5. Se invoca a /result/{id} para obtener el fichero CSV con los resultados.
- name: "F4"
  description: |
    Servicio de obtención de información sobre el sistema
- name: "F5"
  description: |
    Servicio de creación de intersiciales de publicidad en las redirecciones. Primero se devuelve el sponsor y pasado un tiempo se devuelve la URI original. La implementación es con **webSockets**
    - **Secuencia de ejecución**:
        1. Ejecutar /{id}
        2. En el caso en el que haya sponsor, se redirige a un HTML con JavaScript.
        3. El JavaScript interacciona con webSockets con el servidor y este devuelve tras 5 segundos la URI asociada a la acortada
- name: "F6"
  description: "Servicio que devuelve la URI asociada a la acortada"
- name: "F7"
  description: "Servicio de acortador URL con dirección personalizada"

schemes:
- "http"
paths:
  /short:
    post:
      tags:
      - "F7"
      - "F2"
      - "F1"
      summary: "El servicio acortador permite crear una dirección personalizada y, si ésta ya existe, se lo indica al usuario."
      operationId: "createShortURI"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: "uri"
        description: "URI a recortar"
        required: true
        type: string
        format: uri
      - in: query
        name: "periodicity"
        description: "Se desea comprobacion periodica del estado"
        required: true
        type: boolean
      - in: query
        name: "qr"
        description: "Se desea creación de imagen QR"
        type: boolean
        required: true
      - in: query
        name: "sponsor"
        description: "URI del sponsor"
        type: string
        format: "uri"

      responses:
        201:
          description: "URI creada correctamente"
          schema:
            $ref: "#/definitions/ShortenerResponse"
        400:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"
  /{id}:
    get:
      tags:
      - "F6"
      - "F5"
      summary: |
        Servicio que redirige a la URI asociada a la URI acortada. Si la URI tiene sponsor, entonces devuelve la URI del sponsor un HTML con JavaScript que interacciona con el servidor mediante webSockets para obtener tras 5 segundos la URI asociada.
      operationId: "returnURI"
      parameters:
      - in: path
        name: "id"
        description: "id URI acortada"
        type: "string"
        required: true
      produces:
        - application/json
        - text/html
      responses:
        200:
          description: "Intersicial de publicidad"
        307:
          description: "Redireccionamiento correcto"
        404:
          description: "URI no alcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"

  /{id}/qr:
    get:
      tags:
      - "F1"
      summary: |
        Devuelve la imagen QR asociada a la URI acortada.
      operationId: "readURIQR"
      produces:
      - "image/png"
      parameters:
      - in: path
        name: "id"
        description: "Identificador de la URI cuyo código QR ha sido creado."
        type: "string"
        required: true
      responses:
        200:
          description: "Imagen QR"
          schema:
            type: file
        404:
          description: "URI inalcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"


  /uploadCSV:
    post:
      tags:
      - "F3"
      summary: "Servicio que acorta todas las URLs indicadas en un fichero CSV. El fichero debe tener una URI por fila."
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: file
        type: file
        description: "fichero csv"
      responses:
        202:
          description: "Fichero subido, devuelve la URI del trabajo creado en Location en el Header"
        400:
          description: "Fichero CSV malformado"
          schema:
            type: "string"
            example: "Fechero CSV malformado"

  /job/{id}:
    get:
      tags:
      - "F3"
      summary: |
        Devuelve el estado del procesado de las URIs del fichero subido. La cabecera contiene un campo Retry-After para indicar cada cuantos segundos preguntar por el estado de la petición.
      operationId: "jobState"
      parameters:
      - in: path
        name: "id"
        description: "Estado del proceso"
        type: "string"
        required: true
      responses:
        200:
          description: "Estado del proceso."
          schema:
            type: "object"
            properties:
              hash:
                type: string
                example: "0"
              converted:
                type: integer
                example: 25
              total:
                type: integer
                example: 100
              uriResult:
                type: string
                example: http://localhost:8080/result/0
              result:
                type: string
                example: null
        404:
          description: "No existe el trabajo"

  /result/{id}:
    get:
      tags:
      - "F3"
      summary: |
        Devuelve el fichero CSV resultante de haber procesado las URIs.
      operationId: "jobResult"
      produces:
      - application/csv
      parameters:
      - in: path
        name: "id"
        description: "Identificador del recurso"
        type: "string"
        required: true
      responses:
        200:
          description: "Fichero resultado con las URIs procesadas"
          schema:
            type: file
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/ApiResponse"

  /stats:
    get:
      tags:
      - "F4"
      summary: "El servicio devuelve estadísticas globales de uso y carga del sistema."
      operationId: "systemStats"
      produces:
      - "application/json"
      responses:
        200:
          description: "Info. sistema"
          schema:
            $ref: "#/definitions/ApiStatsResponse"
  /{id}/info:
    get:
      tags:
      - "F4"
      summary: "El servicio devuelve estadísticas de uso de la URI con identificador id"
      operationId: "uriStats"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "id"
        description: "Identificador del recurso"
        type: "string"
        required: true
      responses:
        200:
          description: "Info. URI"
          schema:
            $ref: "#/definitions/ApiStatsUri"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/ApiResponse"

  /{id}/alive:
    get:
      tags:
      - "F4"
      - "F2"
      summary: |
        Devuelve un JSON que indica si la URI es alcanzable o no. Si no se deseaba periodiciad el método devuelve 404.
      operationId: "uriStatsAlive"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "id"
        description: "Identificador del recurso"
        type: "string"
        required: true
      responses:
        200:
          description: "URI alcanzable o no"
          schema:
            $ref: "#/definitions/aliveUri"
        400:
          description: "La URI no se comprueba periódicamente"
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  ApiStatsResponse:
    type: "object"
    properties:
      uptime_seconds:
        type: "integer"
      user_number:
        type: "integer"
      uri_number:
        type: "integer"
      click_number:
        type: "integer"
      time_last_redirection:
        type: "string"
        format: date-time
      mem_used_mb:
        type: "integer"
      mem_available_mb:
        type: "integer"
  ApiStatsUri:
    type: "object"
    properties:
      creation_date:
        type: "string"
        format: date
      click_number:
        type: "integer"
      time_last_redirection:
        type: "string"
        format: date-time
  ShortenerResponse:
    type: "object"
    properties:
      hash:
        type: "string"
      target:
        type: "string"
      uri:
        type: "string"
        format: "uri"
      sponsor:
        type: "string"
      created:
        type: "string"
      owner:
        type: "string"
      mode:
        type: "integer"
      safe:
        type: "boolean"
      ip:
        type: "string"
      country:
        type: "string"
  aliveUri:
    type: "object"
    properties:
      alive:
        type: boolean
        example: true