swagger: "2.0"
info:
  description: "A simple URL Shortener with loads of functionalities."
  version: "1.0.0"
  title: "Pink Panther URL Shortener"
host: "localhost"
basePath: "/pink-panther"
tags:
- name: "F1"
  description: "Servicio de transformacion de URI a imagen QR"
- name: "F5"
  description: "Servicio de creación de intersiciales de publicidad en las redirecciones"
schemes:
- "http"
paths:
  /QR/{URIShorted}:
    post:
      tags:
      - "F1"
      summary: "Al enviar la URI a un servicio que la convierta en QR devuelve una imagen que al acceder al contenido corresponde con la URI enviada."
      operationId: "createURIQR"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "URIShorted"
        description: "URI recortada previamente"
        type: "string"
        required: true
      responses:
        200:
          description: "URI correcta"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

  /advert/{URIShorted}:
    get:
      tags:
      - "F5"
      summary: "El servicio devuelve en primer lugar la URI de la web a mostrar su publicidad y pasado un tiempo devuelve la URI asociada a la URI acortada."
      operationId: "advertising"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "URIShorted"
        description: "URI acortada previamente"
        required: true
        schema:
          $ref: "#/definitions/UriAcortada"
      responses:
        200:
          description: "URI correcta"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  UriAcortada:
    type: "object"
    properties:
      slug:
        type: "string"
      uri:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  UriA:
    type: "object"
    properties:
      slug:
        type: "string"
      uri:
        type: "string"