swagger: "2.0"
info:
  description: "A simple URL Shortener with loads of functionalities."
  version: "1.0.0"
  title: "Pink Panther URL Shortener"
host: "localhost:8080"
basePath: "/"
tags:
- name: "F1"
  description: |
    Servicio de transformacion de URI a imagen QR
- name: "F2"
  description: "Servicio que comprueba que una URL se puede alcanzar antes de crear una URL corta"
- name: "F3"
  description: |
    Servicio que permite subir un CSV con todas las URI que se desean acortar y que devuelve un CSV con que contiene para cada URI su URI acortada.
    - Formato de entrada CSV:
      | URIOriginal |
      | ------- |
      | http://midomino.com |
      | http://mirecurso.com |
    - Formato de salida CSV:
      | URIOriginal | URIAcortada |
      | ------- | -------- |
      | http://midomino.com | http://recortada/123 |
      | http://mirecurso.com | http://recortada/321 |
- name: "F4"
  description: "Servicio de obtención de información sobre el sistema"
- name: "F5"
  description: |
    Servicio de creación de intersiciales de publicidad en las redirecciones. Primero se devuelve el sponsor y pasado un tiempo se devuelve la URI original. La implementación es con **webSockets**
    - **Secuencia de ejecución**:
        1. Ejecutar /sponsor/{id}
        2. Ejecutar /{id}
- name: "F6"
  description: "Servicio que devuelve la URI asociada a la acortada"
- name: "F7"
  description: "Servicio de acortador URL con dirección personalizada"

schemes:
- "http"
paths:
  /short:
    post:
      tags:
      - "F7"
      - "F2"
      summary: "El servicio acortador permite crear una dirección personalizada y, si ésta ya existe, se lo indica al usuario."
      operationId: "createShortURI"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: "uri"
        description: "URI a recortar"
        required: true
        type: string
      - in: query
        name: "sponsor"
        description: "URI del sponsor"
        type: string

      responses:
        201:
          description: "URI creada correctamente"
          schema:
            $ref: "#/definitions/ShortenerResponse"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"
  /{id}:
    get:
      tags:
      - "F6"
      - "F5"
      summary: "Servicio que devuelve la URI asociada a la URI acortada"
      operationId: "returnURI"
      parameters:
      - in: path
        name: "id"
        description: "id URI acortada"
        type: "string"
        required: true
      responses:
        307:
          description: "URI alcanzable"
          schema:
            $ref: "#/definitions/AcortarUri"
        200:
          description: "URI alcanzable"
          schema:
            $ref: "#/definitions/AcortarUri"
        404:
          description: "URI no alcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"

  /QR/{id}:
    post:
      tags:
      - "F1"
      summary: "Envia la URI acortada que se corresponde con id a un servicio para que la convierta en QR. El sistema devuelve una imagen QR que corresponde con la URI enviada. Llama a una API SOAP"
      operationId: "createURIQR"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "id"
        description: "URI recortada previamente"
        type: "string"
        required: true
      responses:
        201:
          description: "URI correcta"
          schema:
            $ref: "#/definitions/ApiQRResponse"
        502:
          description: "Servidor QR no responde"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"
        404:
          description: "URI inalcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"

  /shortAndCheck:
    post:
      tags:
      - "F2"
      - "F1"
      - "F3"
      summary: "El servicio comprueba que la URI es alcanzable, devolviendo una URI acortada asociada en caso de que lo sea."
      operationId: "checkAndCreateUri"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: "uri"
        description: "URI a recortar"
        required: true
        type: string
      - in: query
        name: "sponsor"
        description: "URI del sponsor"
        type: string
      responses:
        201:
          description: "URI creada"
          schema:
            $ref: "#/definitions/ShortenerResponse"
        404:
          description: "URI no alcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

  /uploadCSV:
    post:
      tags:
      - "F3"
      summary: "Servicio que acorta todas las URLs indicadas en un fichero CSV. El fichero debe tener una URI por fila."
      consumes:
      - multipart/form-data
      produces:
      - application/csv
      parameters:
      - in: formData
        name: file
        type: file
        description: "fichero csv"
      responses:
        201:
          description: "URIs creadas"
          schema:
            type: file
        400:
          description: "Fichero CSV malformado"
          schema:
            $ref: "#/definitions/ApiResponse"
        404:
          description: "URI no alcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

  /stats:
    get:
      tags:
      - "F4"
      summary: "El servicio devuelve estadísticas de uso y carga del sistema."
      operationId: "systemStats"
      produces:
      - "application/json"
      responses:
        200:
          description: "Info. sistema"
          schema:
            $ref: "#/definitions/ApiStatsResponse"

  /sponsor/{id}:
    get:
      tags:
      - "F5"
      summary: "El servicio devuelve en primer lugar la URI de la web a mostrar su publicidad y pasado un tiempo invoca a F1"
      operationId: "advertising"
      produces:
      - "text/plain"
      parameters:
      - in: path
        name: id
        description: "identificador de la URI acortada"
        required: true
        type: string
      responses:
        200:
          description: "URI del Sponsor Asociado. Si no tiene, se devuelve una URI por defecto."
          schema:
            type: string
            example: "http://www.someMockSponsor.com"
        404:
          description: "URI no alcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  AcortarUri:
    type: "object"
    properties:
      uri:
        type: "string"
      sponsor:
        type: "string"
    example:
      uri: "https://es.stackoverflow.com/"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  ApiSponsorResponse:
    type: "object"
    properties:
      slug:
        type: "string"
      uri:
        type: "string"
  ApiQRResponse:
    type: "object"
    properties:
      uri:
        type: "string"
  ApiStatsResponse:
    type: "object"
    properties:
      uptime_seconds:
        type: "integer"
      user_number:
        type: "integer"
      uri_number:
        type: "integer"
      click_number:
        type: "integer"
      time_last_redirection:
        type: "integer"
      mem_used_mb:
        type: "integer"
      mem_available_mb:
        type: "integer"
  ShortenerResponse:
    type: "object"
    properties:
      hash:
        type: "string"
      target:
        type: "string"
      uri:
        type: "string"
      sponsor:
        type: "string"
      created:
        type: "string"
      owner:
        type: "string"
      mode:
        type: "integer"
      safe:
        type: "boolean"
      ip:
        type: "string"
      country:
        type: "string"