swagger: "2.0"
info:
  description: "A simple URL Shortener with loads of functionalities."
  version: "1.0.0"
  title: "Pink Panther URL Shortener"
host: "localhost"
basePath: "/pink-panther"
tags:
- name: "F1"
  description: "Servicio de transformacion de URI a imagen QR"
- name: "F2"
  description: "Servicio que comprueba que una URL se puede alcanzar antes de crear una URL corta"
- name: "F4"
  description: "Servicio de obtención de información sobre el sistema"
- name: "F5"
  description: "Servicio de creación de intersiciales de publicidad en las redirecciones"
schemes:
- "http"
paths:
  /QR/{URIShorted}:
    post:
      tags:
      - "F1"
      summary: "Al enviar la URI a un servicio que la convierta en QR devuelve una imagen que al acceder al contenido corresponde con la URI enviada."
      operationId: "createURIQR"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "URIShorted"
        description: "URI recortada previamente"
        type: "string"
        required: true
      responses:
        200:
          description: "URI correcta"
          schema:
            $ref: "#/definitions/ApiQRResponse"
        400:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

  /uri/{LongURI}:
    get:
      tags:
      - "F2"
      summary: "El servicio comprueba que la URI es alcanzable, devolviendo una URI acortada asociada en caso de que lo sea."
      operationId: "checkURI"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "LongURI"
        description: "URI a recortar"
        type: "string"
        required: true
      responses:
        200:
          description: "URI alcanzable"
          schema:
            $ref: "#/definitions/UriAcortada"
        404:
          description: "URI no alcanzable"
          schema:
            $ref: "#/definitions/ApiResponse"

  /stats:
    get:
      tags:
      - "F4"
      summary: "El servicio devuelve estadísticas de uso y carga del sistema."
      operationId: "systemStats"
      produces:
      - "application/json"
      responses:
        200:
          description: "Info. sistema"
          schema:
            $ref: "#/definitions/ApiStatsResponse"

  /advert/{URIShorted}:
    get:
      tags:
      - "F5"
      summary: "El servicio devuelve en primer lugar la URI de la web a mostrar su publicidad y pasado un tiempo devuelve la URI asociada a la URI acortada."
      operationId: "advertising"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: URIShorted
        description: "URI deseada"
        required: true
        type: string
      responses:
        200:
          description: "URI de la web de publicidad asociada"
          schema:
            $ref: "#/definitions/ApiAdvertResponse"
        400:
          description: "URI inválida"
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  UriAcortada:
    type: "object"
    properties:
      slug:
        type: "string"
      uri:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  ApiAdvertResponse:
    type: "object"
    properties:
      slug:
        type: "string"
      uri:
        type: "string"
  ApiQRResponse:
    type: "object"
    properties:
      uri:
        type: "string"
  ApiStatsResponse:
    type: "object"
    properties:
      uptime_seconds:
        type: "integer"
      user_number:
        type: "integer"
      uri_number:
        type: "integer"
      click_number:
        type: "integer"
      time_last_redirection:
        type: "integer"
      mem_used_mb:
        type: "integer"
      mem_available_mb:
        type: "integer"